### ISSUE TITLE
Higher contrast + add contour lines

### ISSUE THREAD

**Issue by lxbarth** [osmlab/mapbox-studio-humanitarian-print.tm2#2]
@amyleew - so turns out KLL can't use Mapbox Studio due to low bandwidth.

@geohacker was in touch w/ Prabhas from KLL, they print them black and white. So let's:
- Go higher contrast on roads, buildings
- Make hillshading lighter
- Add contour lines

Per https://github.com/osmlab/mapbox-studio-humanitarian-print.tm2/issues/1#issuecomment-97033078

**Comment by amyleew** [comment]
@lxbarth - Updated prints, slippy, and [/repo](https://github.com/osmlab/mapbox-studio-humanitarian-print.tm2) files with Higher Contrast version and refresh of VT dataset. Also sent updated email.

[Kalinchok, Kuri Village, Central Region, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#17/27.74714/86.03230)
![kuri_z17_bw](https://cloud.githubusercontent.com/assets/4587826/7375422/82358fca-eda6-11e4-85f7-e2d9dc25c04c.png)

[Bahrabise, Central Region, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#14/27.7970573/85.9195447)
![bahrabise_z16_bw](https://cloud.githubusercontent.com/assets/4587826/7375840/4c96beea-eda9-11e4-9033-0d1c6365aa59.jpg)

[Charikot, Bhimeshwor Municipality, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#16/27.6667/86.0529)
![charikot_z16_bw](https://cloud.githubusercontent.com/assets/4587826/7375604/dd494a68-eda7-11e4-8f1e-acf8bdfc7256.png)

[Laprak, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#15/28.2119/84.8069)
![larpak_z15_bw](https://cloud.githubusercontent.com/assets/4587826/7375850/54c257aa-eda9-11e4-83bc-28009448b581.jpg)

[Barpak, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#16/28.2016/84.7448)
![barpak_z16_bw](https://cloud.githubusercontent.com/assets/4587826/7375855/5939cc28-eda9-11e4-9888-7dd1055372dc.jpg)

## Additional Locations

[Kirtipur, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#15/27.674901128890223/85.27832508087158)
![kirtipur_z15_bw](https://cloud.githubusercontent.com/assets/4587826/7375493/1296df88-eda7-11e4-9bcd-418ff81e7d7b.png)

[Chasukhel, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#17/27.67208/85.42993)
![chasukhel_z17_bw](https://cloud.githubusercontent.com/assets/4587826/7375587/b6d484c4-eda7-11e4-953f-ecdb60243391.png)

[Dolakha, Nepal](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#18/27.67795/86.07402)
![dolakha_z18_bw](https://cloud.githubusercontent.com/assets/4587826/7375590/c03a8676-eda7-11e4-820b-7308755092a7.png)

**Comment by lxbarth** [comment]
Fantastic work. Closing here as I see you shared this work with Prabhahs and team Kathmandu Living Labs for getting live on their quake maps site.
