### ISSUE TITLE
Scale for the print maps.

### ISSUE THREAD

**Issue by geohacker** [osmlab/mapbox-studio-humanitarian-print.tm2#3]
@amyleew how can we do this?
Prabhas just pinged asking if we can get a scale on all the maps that we are printing. 

cc @lxbarth

**Comment by lxbarth** [comment]
If we wind up re exporting maps, let's get also fix attribution https://github.com/osmlab/mapbox-studio-humanitarian-print.tm2/issues/4

**Comment by planemad** [comment]
@geohacker can't think of an easy way to do it, unless theres a hidden Studio feature. The scale at each zoom level should be consistent though. If we can calculate that, then its possible to overlay a small graphic using imagemagik? Just a thought.

**Comment by lxbarth** [comment]
Fieldpapers comes with a scale. Let's get [the map](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#9/28.4627/84.1223) up on fieldpapers.

Asked: https://twitter.com/lxbarth/status/593370235568263168

**Comment by planemad** [comment]
@lxbarth neat idea! 
Need to ask Stamen?
https://github.com/stamen/fieldpapers

**Comment by geohacker** [comment]
Saw this http://fieldpapers.org/upload_mbtiles.php
Will try

On Wed, Apr 29, 2015 at 4:34 PM, Arun Ganesh notifications@github.com
wrote:

> @lxbarth https://github.com/lxbarth neat idea!
> Need to ask Stamen?
> https://github.com/stamen/fieldpapers
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/osmlab/mapbox-studio-humanitarian-print.tm2/issues/3#issuecomment-97389047
> .

## 

Sajjad Anwar | W: http://sajjad.in | T: @geohacker

**Comment by amyleew** [comment]
> Saw this http://fieldpapers.org/upload_mbtiles.php

@geohacker - How's this working? Looks like link works for TileMill maps

**Comment by geohacker** [comment]
> @geohacker - How's this working? Looks like link works for TileMill maps

On it.

**Comment by sconnelley** [comment]
Hi Sean here from Stamen. What's the URL Template you want to use?

**Comment by geohacker** [comment]
Hey @sconnelley - thanks for jumping on this. Can we say `hot`?
We'll make this as a reusable HOT print style.

**Comment by geohacker** [comment]
or `humanitarian`

**Comment by sconnelley** [comment]
I pulled this URL Template from the [link](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#9/28.4627/84.1223) above `https://{s}.tiles.mapbox.com/v4/kll.ptthjjor/{z}/{x}/{y}@2x.png?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA`
Is the correct tile template URL?

**Comment by geohacker** [comment]
That's correct, Sean. Sorry, for some reason I thought you were referring to the fieldpapers URL template.

**Comment by sconnelley** [comment]
Should I be getting `401` errors on the tiles while testing  locally?

**Comment by geohacker** [comment]
Hmm, you shouldn't.

**Comment by sconnelley** [comment]
Ok found the issue with 401's, will fix should be ready to go on http://next.fieldpapers.org/ soon

**Comment by geohacker** [comment]
Thank you so much Sean.

On Wednesday, April 29, 2015, Sean Connelley notifications@github.com
wrote:

> Ok found the issue with 401's, will fix should be ready to go on
> http://next.fieldpapers.org/ soon
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/osmlab/mapbox-studio-humanitarian-print.tm2/issues/3#issuecomment-97458026
> .

## 

Sajjad Anwar | W: http://sajjad.in | T: @geohacker

**Comment by sconnelley** [comment]
We're working on an Atlas printing error but shouldn't be long

**Comment by sethfitz** [comment]
Live on http://fieldpapers.org/ as "Humanitarian - Nepal" (for lack of a better name)

**Comment by lxbarth** [comment]
@mojodna - awesome, thank you so much. Documented in readme: https://github.com/osmlab/mapbox-studio-humanitarian-print.tm2#print-these-maps

I will also flag this to team Kathmandu Living Labs now. I hope they can get up
- General fieldpapers link with export instructions
- useful fieldpapers generated PDF's 

on http://kathmandulivinglabs.github.io/quake-maps/

**Comment by sethfitz** [comment]
:+1:

**Comment by lxbarth** [comment]
Spreading the word https://twitter.com/Mapbox/status/593503920674078723
