### ISSUE TITLE
Attribution, connecting the dots

### ISSUE THREAD

**Issue by lxbarth** [osmlab/mapbox-studio-humanitarian-print.tm2#4]
For maps destined for http://kathmandulivinglabs.github.io/quake-maps/ :

Let's make sure we have attribution on all future exports:

> "Map data: (c) OpenStreetMap contributors. Find out more about these maps on http://kathmandulivinglabs.github.io/quake-maps/"

http://kathmandulivinglabs.github.io/quake-maps/ should also link here. Should this be in local language?

**Comment by amyleew** [comment]
@lxbarth - [KLL](http://kathmandulivinglabs.github.io/quake-maps/) link directly to prints we provided - should I add attribution at bottom of images, include in `.tm2` style or both?

**Comment by amyleew** [comment]
![image](https://cloud.githubusercontent.com/assets/4587826/7394343/f3733e3e-ee60-11e4-8630-f3f19b7f19cb.png)

@lxbarth - Attribution updated on `.tm2` file and [slippy](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#15/27.6749/85.2783)

**Comment by lxbarth** [comment]
Great. This is also taken care of with using Fieldpapers now: https://github.com/osmlab/mapbox-studio-humanitarian-print.tm2/issues/3
