### ISSUE TITLE
Refresh data

### ISSUE THREAD

**Issue by lxbarth** [osmlab/mapbox-studio-humanitarian-print.tm2#5]
@amyleew - can you refresh data on maps this morning? How hard would it be to run an hourly refresh from an EC2 box?

cc @aaronlidman

**Comment by amyleew** [comment]
@lxbarth @aaronlidman - data has been refreshed manually

**Comment by lxbarth** [comment]
@amyleew awesome. @amyleew can you refresh again COB Eastern today and first thing tomorrow morning?

**Comment by amyleew** [comment]
@lxbarth Updated. @aaronlidman is working on `makefile` for auto updates.

**Comment by amyleew** [comment]
@lxbarth @aaronlidman - Nightly refresh done!

**Comment by lxbarth** [comment]
@amyleew - can you kick it daily in this upcoming week?

**Comment by amyleew** [comment]
@lxbarth yes! just updated.

**Comment by aaronlidman** [comment]
Got [some issues figured out with node-osmium](https://github.com/osmcode/node-osmium/issues/41) and we now have an hourly cronjob updating vector tiles into the kll account. Should be seamless, I'm watching the cron log and kll account uploads for any snags for a while.

**Comment by amyleew** [comment]
@aaronlidman - Not seeing 1:11pm update... can we check the log on this update? 

![image](https://cloud.githubusercontent.com/assets/4587826/7499257/5fb22c66-f3f4-11e4-98e2-7b68395218b6.png)

And the name doesn't seem to be storing proper timestamp. Thought it was working on that last update?

![image](https://cloud.githubusercontent.com/assets/4587826/7499328/dc80745a-f3f4-11e4-8e5e-9692502b2e5a.png)
