### ISSUE TITLE
Refresh data 2

### ISSUE THREAD

**Issue by amyleew** [osmlab/mapbox-studio-humanitarian-print.tm2#7]
Per chat w/ @aaronlidman, going to run daily update on `kll.ewomvx6r` VT for [print map](https://api.tiles.mapbox.com/v4/kll.ptthjjor/page.html?access_token=pk.eyJ1Ijoia2xsIiwiYSI6IktVRUtfQnMifQ.GJAHJPvusgK_f0NsSXS8QA#14/27.7083/85.3101). Chat next week, 5/18 to see if it's still necessary.

/cc @lxbarth

**Comment by lxbarth** [comment]
:+1:

**Comment by amyleew** [comment]
Data refreshed!

**Comment by amyleew** [comment]
Final refresh made today !

/cc @lxbarth @aaronlidman
